export DESIGN_NICKNAME ?= snitch_cluster
export DESIGN_NAME = snitch_cluster_wrapper
export PLATFORM    = asap7

-include $(BENCH_DESIGN_HOME)/src/$(DESIGN_NICKNAME)/verilog.mk

export SDC_FILE      = $(BENCH_DESIGN_HOME)/$(PLATFORM)/snitch_cluster/constraint.sdc

# Skip SVA assertions
export VERILOG_DEFINES = -D VERILATOR

# SRAM macros generated by bsg_fakeram (auto-generated by setup.sh)
-include $(BENCH_DESIGN_HOME)/src/$(DESIGN_NICKNAME)/dev/generated/sram_macros.mk
export ADDITIONAL_LEFS = $(SRAM_LEFS)
export ADDITIONAL_LIBS = $(SRAM_LIBS)

# Allow remaining small memories to be synthesized as FFs
# Large SRAMs (512x64 TCDM, 128x512 ICache, 64x512 DMA) are mapped to fakerams in tc_sram.sv
export SYNTH_MEMORY_MAX_BITS = 8193

# Skip SAT-based resource sharing (OOM at ~45GB without this)
export SYNTH_ARGS = -flatten -noshare

export CORE_UTILIZATION = 40
export PLACE_DENSITY = 0.65
