export DESIGN_NICKNAME ?= snitch_cluster
export DESIGN_NAME = snitch_cluster_wrapper
export PLATFORM    = asap7

-include $(BENCH_DESIGN_HOME)/src/$(DESIGN_NICKNAME)/verilog.mk

export SDC_FILE      = $(BENCH_DESIGN_HOME)/$(PLATFORM)/snitch_cluster/constraint.sdc

# Skip SVA assertions
export VERILOG_DEFINES = -D VERILATOR

# SRAM macros generated by bsg_fakeram (designs/src/snitch_cluster/dev/generated/sram/)
SRAM_DIR = $(BENCH_DESIGN_HOME)/src/snitch_cluster/dev/generated/sram
export ADDITIONAL_LEFS = $(SRAM_DIR)/fakeram7_256x64/fakeram7_256x64.lef \
                         $(SRAM_DIR)/fakeram7_256x256/fakeram7_256x256.lef \
                         $(SRAM_DIR)/fakeram7_64x512/fakeram7_64x512.lef
export ADDITIONAL_LIBS = $(SRAM_DIR)/fakeram7_256x64/fakeram7_256x64.lib \
                         $(SRAM_DIR)/fakeram7_256x256/fakeram7_256x256.lib \
                         $(SRAM_DIR)/fakeram7_64x512/fakeram7_64x512.lib

# Allow remaining small memories to be synthesized as FFs
# Large SRAMs (512x64 TCDM, 128x512 ICache, 64x512 DMA) are mapped to fakerams in tc_sram.sv
export SYNTH_MEMORY_MAX_BITS = 8193

# Skip SAT-based resource sharing (OOM at ~45GB without this)
export SYNTH_ARGS = -flatten -noshare

export CORE_UTILIZATION = 40
export PLACE_DENSITY = 0.65
