#!/usr/bin/env python3
"""Generate tc_sram.sv replacement and sram_macros.mk from fakeram.cfg.

Reads the fakeram configuration to know available macros, applies mapping
rules to map tc_sram (NumWords, DataWidth) instances to fakeram macros,
and outputs:
  - generated/tc_sram.sv: drop-in replacement with fakeram instantiations
  - generated/sram_macros.mk: makefile fragment with ADDITIONAL_LEFS/LIBS

Mapping rules (in priority order):
  1. Direct match: (NumWords, DataWidth) matches a macro exactly
  2. Address-banked: NumWords = 2 * macro.depth, DataWidth = macro.width
  3. Width-split: DataWidth = 2 * macro.width, NumWords <= macro.depth
  4. Width-padded: NumWords = macro.depth, DataWidth < macro.width
  Everything else falls through to behavioral FF model.
"""

import json
import sys
import os


def load_fakeram_cfg(cfg_path):
    with open(cfg_path) as f:
        cfg = json.load(f)
    return cfg["srams"]


def generate_tc_sram(macros, output_path):
    """Generate tc_sram.sv with fakeram mappings."""

    # Build mapping rules from available macros
    rules = []

    # Sort macros by size (largest first) for matching priority
    for m in sorted(macros, key=lambda x: x["depth"] * x["width"], reverse=True):
        name = m["name"]
        depth = m["depth"]
        width = m["width"]
        addr_bits = (depth - 1).bit_length()

        # Rule: direct match
        rules.append({
            "condition": f"NumPorts == 1 && NumWords == {depth} && DataWidth == {width}",
            "label": f"gen_{depth}x{width}",
            "comment": f"{depth}x{width}: direct → {name}",
            "body": _gen_direct(name, depth, width, addr_bits),
        })

        # Rule: address-banked (2x depth)
        rules.append({
            "condition": f"NumPorts == 1 && NumWords == {depth * 2} && DataWidth == {width}",
            "label": f"gen_{depth * 2}x{width}",
            "comment": f"{depth * 2}x{width}: address-banked → 2x {name}",
            "body": _gen_address_banked(name, depth, width, addr_bits),
        })

        # Rule: width-split (2x width, NumWords <= depth)
        rules.append({
            "condition": f"NumPorts == 1 && NumWords <= {depth} && DataWidth == {width * 2}",
            "label": f"gen_Nx{width * 2}",
            "comment": f"Nx{width * 2}: width-split → 2x {name}",
            "body": _gen_width_split(name, depth, width, addr_bits),
        })

        # Rule: width-padded (exact depth, DataWidth < macro width)
        # Only useful when DataWidth is an odd size that doesn't match anything else
        # We generate this for all macros but it will only match specific cases
        rules.append({
            "condition": f"NumPorts == 1 && NumWords == {depth} && DataWidth < {width} && DataWidth > {width // 2}",
            "label": f"gen_{depth}xpad{width}",
            "comment": f"{depth}x(<{width}): width-padded → {name}",
            "body": _gen_width_padded(name, depth, width, addr_bits),
        })

    # Deduplicate by label (first match wins)
    seen_labels = set()
    unique_rules = []
    for r in rules:
        if r["label"] not in seen_labels:
            seen_labels.add(r["label"])
            unique_rules.append(r)

    # Generate SystemVerilog
    lines = []
    lines.append("// Auto-generated tc_sram replacement for ASAP7 synthesis.")
    lines.append("// Maps large memories to fakeram macros; small memories stay as FFs.")
    lines.append("// Generated by generate_sram_mapping.py from fakeram.cfg.")
    lines.append("// DO NOT EDIT - regenerate by running setup.sh.")
    lines.append("")
    lines.append("module tc_sram #(")
    lines.append("  parameter int unsigned NumWords     = 32'd1024,")
    lines.append("  parameter int unsigned DataWidth    = 32'd128,")
    lines.append("  parameter int unsigned ByteWidth    = 32'd8,")
    lines.append("  parameter int unsigned NumPorts     = 32'd2,")
    lines.append("  parameter int unsigned Latency      = 32'd1,")
    lines.append("  parameter              SimInit      = \"none\",")
    lines.append("  parameter bit          PrintSimCfg  = 1'b0,")
    lines.append("  parameter              ImplKey      = \"none\",")
    lines.append("  // DEPENDENT PARAMETERS, DO NOT OVERWRITE!")
    lines.append("  parameter int unsigned AddrWidth = (NumWords > 32'd1) ? $clog2(NumWords) : 32'd1,")
    lines.append("  parameter int unsigned BeWidth   = (DataWidth + ByteWidth - 32'd1) / ByteWidth,")
    lines.append("  parameter type         addr_t    = logic [AddrWidth-1:0],")
    lines.append("  parameter type         data_t    = logic [DataWidth-1:0],")
    lines.append("  parameter type         be_t      = logic [BeWidth-1:0]")
    lines.append(") (")
    lines.append("  input  logic                 clk_i,")
    lines.append("  input  logic                 rst_ni,")
    lines.append("  input  logic  [NumPorts-1:0] req_i,")
    lines.append("  input  logic  [NumPorts-1:0] we_i,")
    lines.append("  input  addr_t [NumPorts-1:0] addr_i,")
    lines.append("  input  data_t [NumPorts-1:0] wdata_i,")
    lines.append("  input  be_t   [NumPorts-1:0] be_i,")
    lines.append("  output data_t [NumPorts-1:0] rdata_o")
    lines.append(");")
    lines.append("")

    first = True
    for r in unique_rules:
        sep = "  //" + " " + "─" * 66
        lines.append(sep)
        lines.append(f"  // {r['comment']}")
        lines.append(sep)
        keyword = "if" if first else "end else if"
        lines.append(f"  {keyword} ({r['condition']}) begin : {r['label']}")
        lines.append("")
        for line in r["body"]:
            lines.append(f"    {line}")
        lines.append("")
        first = False

    # FF fallback
    lines.append("  // " + "─" * 66)
    lines.append("  // All other sizes: behavioral model (synthesized to FFs)")
    lines.append("  // " + "─" * 66)
    lines.append("  end else begin : gen_ff")
    lines.append("")
    lines.extend(_gen_ff_fallback())
    lines.append("")
    lines.append("  end")
    lines.append("")
    lines.append("endmodule")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Generated {output_path}")
    print(f"  {len(unique_rules)} fakeram mapping rules + FF fallback")


def _gen_direct(name, depth, width, addr_bits):
    """Generate direct 1:1 macro mapping."""
    return [
        f"{name} i_mem (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( addr_i[0] ),",
        f"  .rw0_wd_in   ( wdata_i[0] ),",
        f"  .rw0_rd_out  ( rdata_o[0] )",
        f");",
    ]


def _gen_address_banked(name, depth, width, addr_bits):
    """Generate 2x address-banked macro mapping."""
    return [
        f"logic bank_sel;",
        f"logic bank_sel_q;",
        f"logic [{addr_bits-1}:0] bank_addr;",
        f"logic [{width-1}:0] rd0, rd1;",
        f"",
        f"assign bank_sel  = addr_i[0][{addr_bits}];",
        f"assign bank_addr = addr_i[0][{addr_bits-1}:0];",
        f"",
        f"{name} i_bank0 (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] & ~bank_sel ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( bank_addr ),",
        f"  .rw0_wd_in   ( wdata_i[0] ),",
        f"  .rw0_rd_out  ( rd0 )",
        f");",
        f"",
        f"{name} i_bank1 (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] & bank_sel ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( bank_addr ),",
        f"  .rw0_wd_in   ( wdata_i[0] ),",
        f"  .rw0_rd_out  ( rd1 )",
        f");",
        f"",
        f"always_ff @(posedge clk_i or negedge rst_ni) begin",
        f"  if (!rst_ni) bank_sel_q <= 1'b0;",
        f"  else if (req_i[0]) bank_sel_q <= bank_sel;",
        f"end",
        f"",
        f"assign rdata_o[0] = bank_sel_q ? rd1 : rd0;",
    ]


def _gen_width_split(name, depth, width, addr_bits):
    """Generate 2x width-split macro mapping."""
    full_width = width * 2
    return [
        f"logic [{addr_bits-1}:0] padded_addr;",
        f"assign padded_addr = {{{{({addr_bits}-AddrWidth){{1'b0}}}}, addr_i[0]}};",
        f"",
        f"logic [{width-1}:0] rd_lo, rd_hi;",
        f"",
        f"{name} i_lo (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( padded_addr ),",
        f"  .rw0_wd_in   ( wdata_i[0][{width-1}:0] ),",
        f"  .rw0_rd_out  ( rd_lo )",
        f");",
        f"",
        f"{name} i_hi (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( padded_addr ),",
        f"  .rw0_wd_in   ( wdata_i[0][{full_width-1}:{width}] ),",
        f"  .rw0_rd_out  ( rd_hi )",
        f");",
        f"",
        f"assign rdata_o[0] = {{rd_hi, rd_lo}};",
    ]


def _gen_width_padded(name, depth, width, addr_bits):
    """Generate width-padded macro mapping (DataWidth < macro width)."""
    return [
        f"logic [{addr_bits-1}:0] addr_trunc;",
        f"assign addr_trunc = addr_i[0][{addr_bits-1}:0];",
        f"",
        f"logic [{width-1}:0] rd_padded;",
        f"logic [{width-1}:0] wd_padded;",
        f"assign wd_padded = {{{{{width}-DataWidth{{1'b0}}}}, wdata_i[0]}};",
        f"",
        f"{name} i_mem (",
        f"  .rw0_clk     ( clk_i ),",
        f"  .rw0_ce_in   ( req_i[0] ),",
        f"  .rw0_we_in   ( we_i[0] ),",
        f"  .rw0_addr_in ( addr_trunc ),",
        f"  .rw0_wd_in   ( wd_padded ),",
        f"  .rw0_rd_out  ( rd_padded )",
        f");",
        f"",
        f"assign rdata_o[0] = rd_padded[DataWidth-1:0];",
    ]


def _gen_ff_fallback():
    """Generate behavioral FF model for unmapped sizes."""
    return [
        "    data_t sram [NumWords-1:0];",
        "    addr_t [NumPorts-1:0] r_addr_q;",
        "",
        "    data_t [NumPorts-1:0][Latency-1:0] rdata_q, rdata_d;",
        "    if (Latency == 32'd0) begin : gen_no_read_lat",
        "      for (genvar i = 0; i < NumPorts; i++) begin : gen_port",
        "        assign rdata_o[i] = (req_i[i] && !we_i[i]) ? sram[addr_i[i]] : sram[r_addr_q[i]];",
        "      end",
        "    end else begin : gen_read_lat",
        "      always_comb begin",
        "        for (int unsigned i = 0; i < NumPorts; i++) begin",
        "          rdata_o[i] = rdata_q[i][0];",
        "          for (int unsigned j = 0; j < (Latency-1); j++)",
        "            rdata_d[i][j] = rdata_q[i][j+1];",
        "          rdata_d[i][Latency-1] = (req_i[i] && !we_i[i]) ? sram[addr_i[i]] : sram[r_addr_q[i]];",
        "        end",
        "      end",
        "    end",
        "",
        "    always_ff @(posedge clk_i or negedge rst_ni) begin",
        "      if (!rst_ni) begin",
        "        for (int i = 0; i < NumPorts; i++)",
        "          r_addr_q[i] <= {AddrWidth{1'b0}};",
        "      end else begin",
        "        for (int unsigned i = 0; i < NumPorts; i++) begin",
        "          if (Latency != 0) begin",
        "            for (int unsigned j = 0; j < Latency; j++)",
        "              rdata_q[i][j] <= rdata_d[i][j];",
        "          end",
        "        end",
        "        for (int unsigned i = 0; i < NumPorts; i++) begin",
        "          if (req_i[i]) begin",
        "            if (we_i[i]) begin",
        "              for (int unsigned j = 0; j < BeWidth; j++) begin",
        "                if (be_i[i][j])",
        "                  sram[addr_i[i]][j*ByteWidth+:ByteWidth] <= wdata_i[i][j*ByteWidth+:ByteWidth];",
        "              end",
        "            end else begin",
        "              r_addr_q[i] <= addr_i[i];",
        "            end",
        "          end",
        "        end",
        "      end",
        "    end",
    ]


def generate_sram_macros_mk(macros, sram_dir, output_path):
    """Generate sram_macros.mk with ADDITIONAL_LEFS/LIBS."""
    lines = []
    lines.append("# Auto-generated SRAM macro paths for config.mk")
    lines.append("# Generated by generate_sram_mapping.py from fakeram.cfg.")
    lines.append("# DO NOT EDIT - regenerate by running setup.sh.")
    lines.append("")
    lines.append(f"SRAM_DIR = {sram_dir}")
    lines.append("")

    lef_lines = []
    lib_lines = []
    for m in macros:
        name = m["name"]
        lef_lines.append(f"$(SRAM_DIR)/{name}/{name}.lef")
        lib_lines.append(f"$(SRAM_DIR)/{name}/{name}.lib")

    lines.append("SRAM_LEFS = " + " \\\n            ".join(lef_lines))
    lines.append("SRAM_LIBS = " + " \\\n            ".join(lib_lines))
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Generated {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <fakeram.cfg> [output_dir]")
        sys.exit(1)

    cfg_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "generated"

    macros = load_fakeram_cfg(cfg_path)
    sram_dir = os.path.dirname(cfg_path)

    generate_tc_sram(macros, os.path.join(output_dir, "tc_sram.sv"))
    generate_sram_macros_mk(
        macros,
        "$(BENCH_DESIGN_HOME)/src/snitch_cluster/dev/" + os.path.relpath(sram_dir, "."),
        os.path.join(output_dir, "sram_macros.mk"),
    )
